// Builds schema/dist/ from schema/src/. Six steps, each loud on failure:
//
//   1. meta-validate every src/*.schema.json against draft-07
//   2. generate dist/types.d.ts with the json-schema-to-typescript fork
//   3. precompile Ajv validators into dist/validators.js (+ .d.ts)
//   4. copy the raw schemas into dist/json/
//   5. flatten chat-response into dist/json/tool/respond-input.json for Claude
//   6. tsc --noEmit over the generated types
//
// Run it as `npm run build:schema` from the repo root.

import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import Ajv from 'ajv';
import addFormats from 'ajv-formats';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { compileFromFile } from 'json-schema-to-typescript';
import $RefParser from '@apidevtools/json-schema-ref-parser';

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = join(HERE, '..');
const SRC = join(PKG, 'src');
const DIST = join(PKG, 'dist');

const pkg = JSON.parse(readFileSync(join(PKG, 'package.json'), 'utf8'));
const step = (n, what) => console.log(`[schema] ${n}/6 ${what}`);
const fail = (msg) => {
  console.error(`[schema] BUILD FAILED: ${msg}`);
  process.exit(1);
};

// The named validators consumers get, and the schema each one compiles from.
// Keys must match the exports listed in index.js and dist/validators.d.ts.
//
// The four *Action entries compile a single oneOf branch each. Ajv reports a
// oneOf failure as every branch's complaints at once, with no way to tell which
// branch an error came from — resolving a $ref rewrites schemaPath relative to
// the target. Validating the branch the `op` names gives a usable message.
const VALIDATORS = {
  validateOkrDocument: 'okr-document.schema.json',
  validateOkrTree: 'okr-tree.schema.json',
  validateOkrNode: 'okr-node.schema.json',
  validateCompany: 'company.schema.json',
  validateHistory: 'history.schema.json',
  validateAction: 'action.schema.json',
  validateChatRequest: 'chat-request.schema.json',
  validateChatResponse: 'chat-response.schema.json',
  validateEditAction: 'action.schema.json#/definitions/editAction',
  validateRelinkAction: 'action.schema.json#/definitions/relinkAction',
  validateAddAction: 'action.schema.json#/definitions/addAction',
  validateDeleteAction: 'action.schema.json#/definitions/deleteAction'
};

const BASE = 'https://okr-viewer.dev/schema/v1/';

rmSync(DIST, { recursive: true, force: true });
mkdirSync(join(DIST, 'json', 'tool'), { recursive: true });

const files = readdirSync(SRC).filter((f) => f.endsWith('.schema.json')).sort();
if (!files.length) fail('no schemas found in src/');

// ── 1. meta-validate ────────────────────────────────────────────────────────
step(1, `meta-validating ${files.length} schemas against draft-07`);

// One Ajv instance for everything: adding all schemas up front lets the
// cross-file $refs resolve by $id without a loader.
const ajv = new Ajv({
  allErrors: true,
  strict: true,
  allowUnionTypes: true, // our nullable ids are type: ['string', 'null']
  code: { source: true, esm: true }
});
addFormats(ajv);

const schemas = new Map();
for (const f of files) {
  const schema = JSON.parse(readFileSync(join(SRC, f), 'utf8'));
  if (schema.$id !== BASE + f) fail(`${f}: $id must be "${BASE + f}", got "${schema.$id}"`);
  if (!ajv.validateSchema(schema)) {
    fail(`${f} is not a valid draft-07 schema:\n${ajv.errorsText(ajv.errors, { separator: '\n' })}`);
  }
  schemas.set(f, schema);
  ajv.addSchema(schema, schema.$id);
}

// ── 2. types ────────────────────────────────────────────────────────────────
step(2, 'generating dist/types.d.ts');

const banner = `/* eslint-disable */
/**
 * Generated by json-schema-to-typescript (LudaThomas/json-schema-to-typescript#release)
 * from ${pkg.name}@${pkg.version} schemas in schema/src/.
 *
 * DO NOT EDIT. Change the JSON Schema in schema/src/ and re-run \`npm run build:schema\`.
 */`;

const types = await compileFromFile(join(SRC, 'index.schema.json'), {
  cwd: SRC + '/',
  declareExternallyReferenced: true,
  additionalProperties: false,
  bannerComment: banner,
  style: { singleQuote: true, semi: true, printWidth: 120 }
});

// The whole reason we use the fork: upstream inlines a $ref that has a
// title/description sibling and suffixes the duplicate (OkrNode1). If that
// regresses, the generated types silently fork into near-identical copies.
const dupes = [...new Set(types.match(/^export (?:interface|type) (\w+?\d+)\b/gm) ?? [])];
if (dupes.length) {
  fail(
    `dist/types.d.ts has suffixed duplicate types — the $ref-naming fix regressed:\n  ${dupes.join('\n  ')}\n` +
      `Check that json-schema-to-typescript still resolves to the LudaThomas #release fork.`
  );
}

writeFileSync(join(DIST, 'types.d.ts'), types);

// ── 3. precompiled validators ───────────────────────────────────────────────
step(3, `precompiling ${Object.keys(VALIDATORS).length} Ajv validators`);

const byExport = {};
for (const [name, target] of Object.entries(VALIDATORS)) {
  const [file, pointer] = target.split('#');
  if (!schemas.has(file)) fail(`validator ${name} points at missing schema ${file}`);
  const id = BASE + target;
  if (!ajv.getSchema(id)) fail(`validator ${name}: ${pointer ? `pointer #${pointer} ` : ''}does not resolve in ${file}`);
  byExport[name] = id;
}

let validators;
try {
  validators = standaloneCode(ajv, byExport);
} catch (err) {
  fail(`Ajv standalone compilation failed: ${err.message}`);
}

// Ajv's esm output uses `export` for the validators but still reaches for its
// own runtime helpers with `require()`, which throws in an ES module and would
// not survive bundling either. Hoist each one into a real default import; for
// these CJS modules that binding is module.exports, so the `.default` and
// `.fullFormats` lookups after it still resolve.
// The specifiers are deep paths into CJS packages ("ajv/dist/runtime/ucs2length"),
// which require() resolves extensionlessly but ESM does not.
const required = [...new Set([...validators.matchAll(/require\("([^"]+)"\)/g)].map((m) => m[1]))];
const imports = required.map(
  (mod, i) => `import __dep${i} from ${JSON.stringify(/\.[a-z]+$/.test(mod) ? mod : `${mod}.js`)};`
);
for (const [i, mod] of required.entries()) {
  validators = validators.split(`require(${JSON.stringify(mod)})`).join(`__dep${i}`);
}
if (/\brequire\s*\(/.test(validators)) fail('validators.js still calls require() after the ESM rewrite');

writeFileSync(
  join(DIST, 'validators.js'),
  `/* Generated by schema/scripts/build.mjs. DO NOT EDIT. */\n${imports.join('\n')}\n${validators}`
);
if (required.length) console.log(`[schema]     hoisted ${required.length} Ajv runtime require() calls to imports`);

const validatorTypes = `/* Generated by schema/scripts/build.mjs. DO NOT EDIT. */
/** An Ajv precompiled validator: returns true/false and parks failures on \`.errors\`. */
export interface CompiledValidator {
  (data: unknown): boolean;
  errors?: null | { instancePath: string; schemaPath: string; keyword: string; message?: string; params: Record<string, unknown> }[];
}
${Object.keys(VALIDATORS)
  .map((name) => `export declare const ${name}: CompiledValidator;`)
  .join('\n')}
`;
writeFileSync(join(DIST, 'validators.d.ts'), validatorTypes);

// ── 4. raw schema copies ────────────────────────────────────────────────────
step(4, `copying ${files.length} schemas to dist/json/`);
for (const [f, schema] of schemas) {
  writeFileSync(join(DIST, 'json', f), JSON.stringify(schema, null, 2) + '\n');
}

// ── 5. flattened tool schema ────────────────────────────────────────────────
step(5, 'flattening dist/json/tool/respond-input.json');

// Claude's `input_schema` cannot follow external $refs, so the tool gets a
// fully dereferenced copy. Descriptions carry over from src/, which is why
// every property in the schemas is written for the model as well as for us.
// Dereferencing splices whole files in, so the inlined copies bring their own
// $schema/$id and their now-unreachable definitions with them. Strip those
// everywhere, not just at the root.
const DROP = new Set(['$schema', '$id', '$comment', 'definitions']);
const prune = (node, seen = new Map()) => {
  if (Array.isArray(node)) return node.map((v) => prune(v, seen));
  if (!node || typeof node !== 'object') return node;
  if (seen.has(node)) return seen.get(node);
  const out = {};
  seen.set(node, out);
  for (const [k, v] of Object.entries(node)) if (!DROP.has(k)) out[k] = prune(v, seen);
  return out;
};

const tool = prune(await $RefParser.dereference(join(SRC, 'chat-response.schema.json')));
tool.required = ['reply', 'actions', 'highlight'];

const leftover = JSON.stringify(tool).match(/"\$(ref|id|schema)"/g);
if (leftover) fail(`respond-input.json still contains ${leftover.join(', ')} after dereferencing`);

writeFileSync(join(DIST, 'json', 'tool', 'respond-input.json'), JSON.stringify(tool, null, 2) + '\n');

// index.js is bundled for the browser as well as loaded by the service, so it
// cannot read package.json off disk or use a JSON import attribute. Bake both
// into a plain ESM module instead.
writeFileSync(
  join(DIST, 'meta.js'),
  `/* Generated by schema/scripts/build.mjs. DO NOT EDIT. */
export const PACKAGE_VERSION = ${JSON.stringify(pkg.version)};
export const RESPOND_INPUT_SCHEMA = ${JSON.stringify(tool, null, 2)};
`
);
writeFileSync(
  join(DIST, 'meta.d.ts'),
  `/* Generated by schema/scripts/build.mjs. DO NOT EDIT. */
export declare const PACKAGE_VERSION: string;
export declare const RESPOND_INPUT_SCHEMA: Record<string, unknown>;
`
);

// ── 6. type-check ───────────────────────────────────────────────────────────
step(6, 'type-checking generated declarations');

// npm hoists devDeps to the workspace root, so resolve tsc rather than
// assuming it sits in schema/node_modules.
const tsc = createRequire(import.meta.url).resolve('typescript/bin/tsc');
try {
  // tsconfig.check.json rather than CLI flags: it pins lib/moduleResolution and
  // sets `types: []`, so the check sees our declarations and nothing a hoisted
  // @types/* package happens to drag in.
  execFileSync(process.execPath, [tsc, '-p', 'tsconfig.check.json'], { cwd: PKG, stdio: 'pipe', encoding: 'utf8' });
} catch (err) {
  fail(`tsc rejected the generated declarations:\n${err.stdout ?? ''}${err.stderr ?? ''}`);
}

console.log(`[schema] built ${pkg.name}@${pkg.version} → dist/`);
